# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WoMa
email: woma@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Code / Music / Generative Art
baseurl: "/woma" # the subpath of your site, e.g. /blog
url: "https://mathieuguillout.github.io/" # the base hostname & protocol for your site
github_username:  MathieuGuillout

# Build settings
markdown: kramdown
